export const Datas = [
  { "id": 1, "name": "SKU*" },
  { "id": 2, "name": "Quantity*" },
  { "id": 3, "name": "Price*" },
  { "id": 4, "name": "DateAvailable*" },
  { "id": 5, "name": "Name*" },
  { "id": 6, "name": "Images*" },
  { "id": 7, "name": "Category1*" },
  { "id": 8, "name": "UPC" },
  { "id": 9, "name": "HSN" },
  { "id": 10, "name": "Tax_Type" },
  { "id": 11, "name": "Tax" },
  { "id": 12, "name": "Description" },
  { "id": 13, "name": "Model" },
  { "id": 14, "name": "Condition" },
  { "id": 15, "name": "Manufacturer_Name" },
  { "id": 16, "name": "Manufacturer_Image" },
  { "id": 17, "name": "Manufacturer_Status" },
  { "id": 18, "name": "Stock_Status_Id" },
  { "id": 19, "name": "MetaTagTitle" },
  { "id": 20, "name": "MetaTagDescription" },
  { "id": 21, "name": "MetaTagKeyword" },
  { "id": 22, "name": "ProductSlug" },
  { "id": 23, "name": "Category1_Sort_Order" },
  { "id": 24, "name": "Category2" },
  { "id": 25, "name": "Category2_Sort_Order" },
  { "id": 26, "name": "RelatedProductId" },
  { "id": 27, "name": "Required_Shipping" },
  { "id": 28, "name": "Height" },
  { "id": 29, "name": "Weight" },
  { "id": 30, "name": "Width" },
  { "id": 31, "name": "Length" },
  { "id": 32, "name": "Package_Cost" },
  { "id": 33, "name": "Shipping_Cost" },
  { "id": 34, "name": "VendorId" },
  { "id": 35, "name": "Variant_Name1" },
  { "id": 36, "name": "Variant_Value1" },
  { "id": 37, "name": "Variant_Name2" },
  { "id": 38, "name": "Variant_Value2" },
  { "id": 39, "name": "Variant_sku" },
  { "id": 40, "name": "Variant_Quantity" },
  { "id": 41, "name": "Variant_Image" },
  { "id": 42, "name": "Variant_Price" },
  { "id": 43, "name": "Variant_OriginalPrice" },
  { "id": 44, "name": "Attribute_Group_1" },
  { "id": 45, "name": "Attribute_Name_1" },
  { "id": 46, "name": "Attribute_Value_1" },
  { "id": 47, "name": "Attribute_Group_2" },
  { "id": 48, "name": "Attribute_Name_2" },
  { "id": 49, "name": "Attribute_Value_2" },
  { "id": 50, "name": "Discount_Quantity_1" },
  { "id": 51, "name": "Discount_Priority_1" },
  { "id": 52, "name": "Discount_Price_1" },
  { "id": 53, "name": "Discount_Date_Start_1" },
  { "id": 54, "name": "Discount_Date_End_1" },
  { "id": 55, "name": "Discount_Quantity_2" },
  { "id": 56, "name": "Discount_Priority_2" },
  { "id": 57, "name": "Discount_Price_2" },
  { "id": 58, "name": "Discount_Date_Start_2" },
  { "id": 59, "name": "Discount_Date_End_2" },
  { "id": 60, "name": "Product_Special_Priority_1" },
  { "id": 61, "name": "Product_Special_Price_1" },
  { "id": 62, "name": "Product_Special_Start_Date_1" },
  { "id": 63, "name": "Product_Special_End_Date_1" },
  { "id": 64, "name": "Product_Special_Priority_2" },
  { "id": 65, "name": "Product_Special_Price_2" },
  { "id": 66, "name": "Product_Special_Start_Date_2" },
  { "id": 67, "name": "Product_Special_End_Date_2" },
  { "id": 68, "name": "Has_Tire_Price" },
  { "id": 69, "name": "Product_Tire_Quantity_1" },
  { "id": 70, "name": "Product_Tire_Price_1" },
  { "id": 71, "name": "Product_Tire_Quantity_2" },
  { "id": 72, "name": "Product_Tire_Price_2" },
  { "id": 73, "name": "Video_Link" },
  { "id": 74, "name": "Import_Type" }
]





export const categoryData = [
  { "id": 1, "name": "Category_Name*" },
  { "id": 2, "name": "Sort_Order*" },
  { "id": 3, "name": "Status*" },
  { "id": 4, "name": "Category_Slug_Name" },
  { "id": 5, "name": "Category_Description" },
  { "id": 6, "name": "Parent_Category" },
  { "id": 7, "name": "Image" },
]