import { Validators } from "@angular/forms";

export const customTable = [
  {
    displayName: "Customers.Customer.Address",
    id: "name",
    type: "default",
    checked: true,
  },
  {
    displayName: "Customers.Customer.City",
    id: "city",
    type: "default",
    checked: true,
  },
  {
    displayName: "Customers.Customer.State",
    id: "stateName",
    type: "default",
    checked: true,
  },
  {
    displayName: "Customers.Customer.phoneNumber",
    id: "phoneNo",
    type: "default",
    checked: true,
  },
  {
    displayName: "Customers.Customer.pinCode",
    id: "postcode",
    type: "default",
    checked: true,
  },
  {
    displayName: "Customers.Customer.AddressType",
    type: "template",
    id: "addressType",
    checked: true,
  },
  {
    displayName: "Customers.Customer.Action",
    id: "menu",
    type: "threeDotMenu",
    checked: true,
    menuData: [
      {
        name: "Edit",
        img: "assets/img/edit.svg",
        displayName: "Customers.Customer.Edit",
      },
      {
        name: "Delete",
        img: "assets/img/delete-new.svg",
        displayName: "Customers.Customer.Delete",
      },
    ],
  },
];

// export const formFields = {
//   Name: {
//     label: "Customers.Customer.Name",
//     name: "name",
//     aliasName: "",
//     validatiors: [],
//     type: "text",
//     placeholder: "placeholder.Name",
//   },
//   Address1: {
//     label: "Customers.Customer.AddressLine1",
//     name: "address1",
//     aliasName: "",
//     validatiors: [Validators.required, Validators.maxLength(128)],
//     type: "text",
//     placeholder: "Customers.CustomerPlaceholder.AddressLine1",
//     mandatory: true,
//   },
//   Address2: {
//     label: "Customers.Customer.AddressLine2",
//     name: "address2",
//     aliasName: "",
//     validatiors: [],
//     type: "text",
//     placeholder: "Customers.CustomerPlaceholder.AddressLine2",
//   },
//   city: {
//     label: "Customers.Customer.City",
//     name: "city",
//     aliasName: "",
//     validatiors: [
//       Validators.required,
//       Validators.maxLength(128),
//       Validators.pattern("[a-zA-Z '-,;.]*"),
//     ],
//     type: "text",
//     placeholder: "Customers.CustomerPlaceholder.City",
//     mandatory: true,
//   },
//   CountryId: {
//     label: "marketplace.seller.Country",
//     name: "CountryId",
//     aliasName: "",
//     validatiors: [Validators.required],
//     type: "ngSelect",
//     placeholder: "placeholder.select country",
//     customData: {
//       data: [{}],
//       key: "name",
//       value: "countryId",
//     },
//     mandatory: true,
//   },
//   StateId: {
//     label: "common.State",
//     name: "StateId",
//     aliasName: "",
//     validatiors: [Validators.required],
//     type: "ngSelect",
//     placeholder: "common.State",
//     customData: {
//       data: [{}],
//       key: "name",
//       value: "zoneId",
//     },
//     mandatory: true,
//   },
//   Pincode: {
//     label: "Customers.Customer.PostalCode",
//     name: "pincode",
//     aliasName: "",
//     validatiors: [
//       Validators.required,
//       Validators.minLength(0),
//       Validators.maxLength(6),
//     ],
//     type: "number",
//     placeholder: "Customers.CustomerPlaceholder.PostalCode",
//     mandatory: true,
//   },
//   AddressType: {
//     label: "Customers.Customer.AddressType",
//     name: "addresstype",
//     aliasName: "",
//     validatiors: [Validators.required],
//     type: "radio",
//     placeholder: "Customers.CustomerPlaceholder.PostalCode",
//     customData: {
//       data: [
//         { name: "Home", id: "1" },
//         { name: "Work", id: "0" },
//       ],
//       key: "name",
//       value: "id",
//     },
//     mandatory: true,
//   },
// };
const ALLOWED_PATTERN = /^[a-zA-Z\s]*$/;
export const formFields = {
  firstName: {
    label: "Customers.Customer.FirstName",
    name: "firstName",
    aliasName: "",
    validatiors: [Validators.required, Validators.maxLength(128),Validators.pattern(/^[a-zA-Z\s]*$/),],
    type: "text",
    mandatory: true,
    placeholder: "Customers.Customer.FirstName",
    optionalErrorMessage: { pattern: "ValidationsErrorMessage.Allowonlyalphabetsspaces" },

  },
  lastName: {
    label: "Customers.Customer.LastName",
    name: "lastName",
    aliasName: "",
    validatiors: [Validators.pattern(/^[a-zA-Z\s]*$/),],
    type: "text",
    placeholder: "Customers.Customer.LastName",
    optionalErrorMessage: { pattern: "ValidationsErrorMessage.Allowonlyalphabetsspaces" },

  },
  phoneNumber: {
    label: "Customers.Customer.phoneNumber",
    name: "phoneNumber",
    aliasName: "",
    validatiors: [Validators.required,Validators.maxLength(15)],
    type: "number",
    mandatory: true,
    placeholder: "Customers.Customer.phoneNumber",
  },
  address1: {
    label: "Customers.Customer.address1Placeholder",
    name: "address1",
    aliasName: "",
    validatiors: [Validators.required],
    type: "text",
    mandatory: true,
    placeholder: "Customers.Customer.address1Placeholder",
  },
  address2: {
    label: "Customers.Customer.address2Placeholder",
    name: "address2",
    aliasName: "",
    validatiors: [Validators.required],
    type: "text",
    mandatory: true,
    placeholder: "Customers.Customer.address2Placeholder",
  },
  landmark: {
    label: "Customers.Customer.landmark",
    name: "landmark",
    aliasName: "",
    validatiors: [],
    type: "text",
    placeholder: "Customers.Customer.landmark",
  },
  city: {
    label: "Customers.Customer.City",
    name: "city",
    aliasName: "",
    validatiors: [
      Validators.required,
      Validators.maxLength(128),
      Validators.pattern("[a-zA-Z '-,;.]*"),
    ],
    type: "text",
    placeholder: "Customers.CustomerPlaceholder.City",
    mandatory: true,
  },
  CountryId: {
    label: "marketplace.seller.Country",
    name: "CountryId",
    aliasName: "",
    validatiors: [Validators.required],
    type: "ngSelect",
    placeholder: "placeholder.select country",
    customData: {
      data: [{}],
      key: "name",
      value: "countryId",
    },
    mandatory: true,
  },

  StateId: {
    label: "common.State",
    name: "StateId",
    aliasName: "",
    validatiors: [Validators.required],
    type: "ngSelect",
    placeholder: "common.State",
    customData: {
      data: [{}],
      key: "name",
      value: "zoneId",
    },
    mandatory: true,
  },

  Pincode: {
    label: "Customers.Customer.pinCode",
    name: "pincode",
    aliasName: "",
    validatiors: [
      Validators.required,
      Validators.maxLength(6),
    ],
    type: "number",
    placeholder: "Customers.Customer.pinCode",
    mandatory: true,
  },
  AddressType: {
    label: "Customers.Customer.AddressType",
    name: "addresstype",
    aliasName: "",
    validatiors: [Validators.required],
    type: "radio",
    placeholder: "Customers.CustomerPlaceholder.PostalCode",
    customData: {
      // data: [
      //   { name: "Billing", id: "1",displayName:"Customers.Customer.Billing"},
      //   { name: "Shipping", id: "0", displayName: "Customers.Customer.Shipping"},
      // ],
      data: [
        { name: "Billing", id: "1",displayName:"Customers.Customer.Billing" },
        { name: "Shipping", id: "0" ,displayName:"Customers.Customer.Shipping"},
      ],
      key: "name",
      value: "id",
    },
    mandatory: true,
  },
};
